# ==================================================================
# 🤖 THE HEXAGON (System Generated)
# ==================================================================
hexagon:
  ontos:
    id: de5395a2-bbe9-4594-825a-17529405e74a
    type: mmd
    owner: Swarmlord
  chronos:
    status: active
    urgency: 0.5
    decay: 0.5
    created: '2025-11-23T10:20:43.112359+00:00'
  topos:
    address: core_memory.mmd
    links: []
  telos:
    viral_factor: 0.0
    meme: core_memory.mmd


graph TD
    hfo_gem_gen_6_original_gem_md["hfo_gem/gen_6/origin"] --> hfo_gem_2025_11_14_gen_6_original_gem_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_5_original_gem_md["hfo_gem/gen_5/origin"] --> hfo_gem_2025_11_14_gen_5_original_gem_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_3_deep_dive_md["hfo_gem/gen_3/deep_d"] --> hfo_gem_2025_11_14_gen_3_deep_dive_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_2_original_gem_md["hfo_gem/gen_2/origin"] --> hfo_gem_2025_11_14_gen_2_original_gem_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_6_summary_md["hfo_gem/gen_6/summar"] --> hfo_gem_2025_11_14_gen_6_summary_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_5_summary_md["hfo_gem/gen_5/summar"] --> hfo_gem_2025_11_14_gen_5_summary_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_5_deep_dive_md["hfo_gem/gen_5/deep_d"] --> hfo_gem_2025_11_14_gen_5_deep_dive_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_3_original_gem_md["hfo_gem/gen_3/origin"] --> hfo_gem_2025_11_14_gen_3_original_gem_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_2_summary_md["hfo_gem/gen_2/summar"] --> hfo_gem_2025_11_14_gen_2_summary_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_2_deep_dive_md["hfo_gem/gen_2/deep_d"] --> hfo_gem_2025_11_14_gen_2_deep_dive_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_6_deep_dive_md["hfo_gem/gen_6/deep_d"] --> hfo_gem_2025_11_14_gen_6_deep_dive_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_4_original_gem_md["hfo_gem/gen_4/origin"] --> hfo_gem_2025_11_14_gen_4_original_gem_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_3_summary_md["hfo_gem/gen_3/summar"] --> hfo_gem_2025_11_14_gen_3_summary_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_4_summary_md["hfo_gem/gen_4/summar"] --> hfo_gem_2025_11_14_gen_4_summary_md["hfo_gem_2025_11_14/g"]
    hfo_gem_gen_4_deep_dive_md["hfo_gem/gen_4/deep_d"] --> hfo_gem_2025_11_14_gen_4_deep_dive_md["hfo_gem_2025_11_14/g"]
