#!/usr/bin/env python3
"""
🦅 Hive Fleet Obsidian: Genesis Protocol (Gen 51)
Usage: python genesis.py [scan|evolve]

- scan: Validates the biological anatomy (Default).
- evolve: Transmutes Brain (Gherkin) into Body (Code).
"""

import sys
import yaml
import re
import subprocess
from pathlib import Path
from rich.console import Console
from rich.tree import Tree

console = Console()


class GenesisScanner:
    """The Observer: Validates the health of the Hive."""

    def __init__(self):
        self.registry_path = Path("brain/registry.yaml")

    def scan(self):
        """Validates that the biological organs exist."""
        console.print("[bold blue]🔍 Scanning HFO Anatomy...[/bold blue]")

        # Load the Holocron
        try:
            with open(self.registry_path, "r") as f:
                registry = yaml.safe_load(f)
        except FileNotFoundError:
            console.print(
                "[bold red]❌ CRITICAL: The Brain (brain/registry.yaml) is missing![/bold red]"
            )
            sys.exit(1)

        anatomy_tree = Tree("🦅 [bold]Hive Fleet Obsidian[/bold]")
        all_healthy = True

        for organ_name, data in registry.get("organs", {}).items():
            path = Path(data["path"])
            if path.exists():
                status = "✅ [green]Healthy[/green]"
            else:
                status = "❌ [red]Missing[/red]"
                all_healthy = False

            organ_node = anatomy_tree.add(f"{organ_name.capitalize()} ({status})")
            organ_node.add(f"Role: [cyan]{data.get('primary_seat', 'Unknown')}[/cyan]")
            organ_node.add(
                f"Function: [yellow]{data.get('biological_function', 'Unknown')}[/yellow]"
            )

        console.print(anatomy_tree)
        self._check_environment()

        if not all_healthy:
            console.print(
                "\n[bold red]⚠️  The Hive is wounded. Please repair missing organs.[/bold red]"
            )
            sys.exit(1)
        else:
            console.print(
                "\n[bold green]✨ The Hive is biologically sound.[/bold green]"
            )

    def _check_environment(self):
        """Checks if the Python environment is correctly set up."""
        console.print("\n[bold blue]🔍 Checking Environment...[/bold blue]")

        # Check Python version
        py_version = sys.version.split()[0]
        console.print(f"Python Version: [green]{py_version}[/green]")

        # Check if inside venv
        in_venv = sys.prefix != sys.base_prefix
        if in_venv:
            console.print("Virtual Environment: [green]Active[/green]")
        else:
            console.print(
                "Virtual Environment: [yellow]Inactive (Recommended to use venv)[/yellow]"
            )


class GenesisFactory:
    """The Evolutionary Forge: Turns Intent into Implementation."""

    def __init__(self):
        self.brain_path = Path("brain")
        self.body_path = Path("body")

    def evolve(self):
        console.print("[bold purple]🧬 Initiating Genesis Evolution...[/bold purple]")
        features = list(self.brain_path.glob("*.feature"))
        console.print(f"Found {len(features)} synaptic patterns (Features).")

        for feature_file in features:
            self._transmute(feature_file)

    def _transmute(self, feature_file: Path):
        # Simple parser to extract feature name and scenarios
        content = feature_file.read_text()
        match = re.search(r"Feature: (.+)", content)
        if not match:
            return

        feature_name = match.group(1).strip()
        slug = feature_file.stem.lower().replace(" ", "_")

        # Determine target organ based on filename or content
        # Defaulting to body/hands/ for workflows, but could be smarter
        target_dir = self.body_path / "hands"
        target_file = target_dir / f"{slug}.py"

        if not target_file.exists():
            self._gestate_code(target_file, feature_name, feature_file.name)
        else:
            # console.print(f"[dim]⚡ {target_file.name} exists. Skipping.[/dim]")
            pass

    def _gestate_code(
        self, target_file: Path, feature_name: str, feature_filename: str
    ):
        console.print(f"[green]🌱 Gestating: {target_file}[/green]")

        # Create a skeleton Python file based on the feature
        code = f'''"""
🦅 Hive Fleet Obsidian: {feature_name}
Generated by Genesis Protocol from {feature_filename}

Intent: {feature_name}
"""

import pytest
from pytest_bdd import scenario, given, when, then

# Ensure the feature file path is correct relative to this file
FEATURE_FILE = "../../brain/{feature_filename}"

@scenario(FEATURE_FILE, "{feature_name}")
def test_{target_file.stem}():
    """Scenario: {feature_name}"""
    pass

# TODO: Implement steps generated from Gherkin
'''
        # Ensure directory exists
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(code)


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "evolve":
        factory = GenesisFactory()
        factory.evolve()
    else:
        scanner = GenesisScanner()
        scanner.scan()

        # Optional: Run smoke tests if requested
        if "--venom" in sys.argv:
            console.print("\n[bold blue]🧪 Venom Protocol[/bold blue]")
            console.print("[bold]🚀 Injecting Venom...[/bold]")
            subprocess.run(["make", "test-all"])


if __name__ == "__main__":
    main()
