#!/usr/bin/env python3
"""
🦅 Hive Fleet Obsidian: Genesis Protocol (Gen 51)
Usage: python genesis.py [scan|evolve]

- scan: Validates the biological anatomy (Default).
- evolve: Transmutes Brain (Gherkin) into Body (Code).
"""

import sys
import yaml
import re
import uuid
import datetime
import subprocess
from pathlib import Path
from rich.console import Console
from rich.tree import Tree

console = Console()


class GenesisScanner:
    """The Observer: Validates the health of the Hive."""

    def __init__(self):
        self.registry_path = Path("brain/registry.yaml")

    def scan(self):
        """Validates that the biological organs exist."""
        console.print("[bold blue]🔍 Scanning HFO Anatomy...[/bold blue]")

        # Load the Holocron
        try:
            with open(self.registry_path, "r") as f:
                registry = yaml.safe_load(f)
        except FileNotFoundError:
            console.print(
                "[bold red]❌ CRITICAL: The Brain (brain/registry.yaml) is missing![/bold red]"
            )
            sys.exit(1)

        anatomy_tree = Tree("🦅 [bold]Hive Fleet Obsidian[/bold]")
        all_healthy = True

        for organ_name, data in registry.get("organs", {}).items():
            path = Path(data["path"])
            if path.exists():
                status = "✅ [green]Healthy[/green]"
            else:
                status = "❌ [red]Missing[/red]"
                all_healthy = False

            organ_node = anatomy_tree.add(f"{organ_name.capitalize()} ({status})")
            organ_node.add(f"Role: [cyan]{data.get('primary_seat', 'Unknown')}[/cyan]")
            organ_node.add(
                f"Function: [yellow]{data.get('biological_function', 'Unknown')}[/yellow]"
            )

        console.print(anatomy_tree)
        self._check_environment()

        if not all_healthy:
            console.print(
                "\n[bold red]⚠️  The Hive is wounded. Please repair missing organs.[/bold red]"
            )
            sys.exit(1)
        else:
            console.print(
                "\n[bold green]✨ The Hive is biologically sound.[/bold green]"
            )

    def _check_environment(self):
        """Checks if the Python environment is correctly set up."""
        console.print("\n[bold blue]🔍 Checking Environment...[/bold blue]")

        # Check Python version
        py_version = sys.version.split()[0]
        console.print(f"Python Version: [green]{py_version}[/green]")

        # Check if inside venv
        in_venv = sys.prefix != sys.base_prefix
        if in_venv:
            console.print("Virtual Environment: [green]Active[/green]")
        else:
            console.print(
                "Virtual Environment: [yellow]Inactive (Recommended to use venv)[/yellow]"
            )


class GenesisFactory:
    """The Evolutionary Forge: Turns Intent into Implementation."""

    def __init__(self):
        self.brain_path = Path("brain")
        self.body_path = Path("body")

    def evolve(self):
        console.print("[bold purple]🧬 Initiating Genesis Evolution...[/bold purple]")
        features = list(self.brain_path.glob("*.feature"))
        console.print(f"Found {len(features)} synaptic patterns (Features).")

        for feature_file in features:
            self._transmute(feature_file)

    def _transmute(self, feature_file: Path):
        # Simple parser to extract feature name and scenarios
        content = feature_file.read_text()
        match = re.search(r"Feature: (.+)", content)
        if not match:
            return

        feature_name = match.group(1).strip()
        slug = feature_file.stem.lower().replace(" ", "_")

        # Determine target organ based on filename or content
        # Defaulting to body/hands/ for workflows, but could be smarter
        target_dir = self.body_path / "hands"
        target_file = target_dir / f"{slug}.py"

        if not target_file.exists():
            self._gestate_code(target_file, feature_name, feature_file.name)
        else:
            # console.print(f"[dim]⚡ {target_file.name} exists. Skipping.[/dim]")
            pass

    def _gestate_code(
        self, target_file: Path, feature_name: str, feature_filename: str
    ):
        console.print(f"[green]🌱 Gestating: {target_file}[/green]")

        # Create a skeleton Python file based on the feature
        code = f'''"""
🦅 Hive Fleet Obsidian: {feature_name}
Generated by Genesis Protocol from {feature_filename}

Intent: {feature_name}
"""

import pytest
from pytest_bdd import scenario, given, when, then

# Ensure the feature file path is correct relative to this file
FEATURE_FILE = "../../brain/{feature_filename}"

@scenario(FEATURE_FILE, "{feature_name}")
def test_{target_file.stem}():
    """Scenario: {feature_name}"""
    pass

# TODO: Implement steps generated from Gherkin
'''
        # Ensure directory exists
        target_file.parent.mkdir(parents=True, exist_ok=True)
        target_file.write_text(code)

    def crystallize(self):
        """Injects the Hexagonal Holon Header into all Markdown files."""
        console.print("[bold cyan]💎 Initiating Great Crystallization...[/bold cyan]")

        # Scan Brain and Body for Markdown files
        targets = list(self.brain_path.rglob("*.md")) + list(
            self.body_path.rglob("*.md")
        )
        console.print(f"Found {len(targets)} potential crystals.")

        for file_path in targets:
            self._process_markdown(file_path)

    def _process_markdown(self, file_path: Path):
        try:
            content = file_path.read_text(encoding="utf-8")

            # Split YAML frontmatter
            if not content.startswith("---"):
                # console.print(f"[dim]  Skipping {file_path.name} (No frontmatter)[/dim]")
                return

            parts = content.split("---", 2)
            if len(parts) < 3:
                return

            yaml_text = parts[1]
            body = parts[2]

            # Parse Face
            try:
                face = yaml.safe_load(yaml_text)
            except yaml.YAMLError:
                console.print(f"[red]❌ Invalid YAML in {file_path.name}[/red]")
                return

            if not isinstance(face, dict):
                return

            if "hexagon" in face:
                # console.print(f"[dim]  ✨ {file_path.name} already crystallized.[/dim]")
                return

            # Generate Hexagon
            hexagon = self._generate_hexagon(face, file_path)

            # Merge and Write
            face["hexagon"] = hexagon

            # Reconstruct File
            new_yaml = yaml.dump(face, sort_keys=False, allow_unicode=True)

            # Add comments for visual separation
            new_yaml = new_yaml.replace(
                "hexagon:",
                "\n# ==================================================================\n# 🤖 THE HEXAGON (System Generated)\n# ==================================================================\nhexagon:",
            )

            new_content = f"---\n{new_yaml}---\n{body}"
            file_path.write_text(new_content, encoding="utf-8")
            console.print(f"[green]  💎 Crystallized: {file_path.name}[/green]")

        except Exception as e:
            console.print(f"[red]  ❌ Error processing {file_path.name}: {e}[/red]")

    def _generate_hexagon(self, face_data: dict, file_path: Path) -> dict:
        """Computes the Hexagon based on the Face and File Context."""

        # 1. ONTOS (Identity)
        ontos = {
            "id": str(uuid.uuid4()),
            "type": "doc",  # Default to doc for markdown
            "owner": "Swarmlord",  # Default owner
        }

        # 2. CHRONOS (Thermodynamics)
        tags = face_data.get("tags", [])
        urgency = 0.1 if "test" in tags else 0.5
        chronos = {
            "status": "active",
            "urgency": urgency,
            "decay": 0.5,
            "created": datetime.datetime.utcnow().isoformat() + "Z",
        }

        # 3. TOPOS (Connectivity)
        # Map directory structure to address
        # brain -> 1, body -> 2, carapace -> 3
        parts = file_path.parts
        address = "0.0.0"
        if "brain" in parts:
            address = "1.0.0"
        elif "body" in parts:
            address = "2.0.0"
        elif "carapace" in parts:
            address = "3.0.0"

        topos = {"address": address, "links": []}

        # 4. TELOS (Purpose)
        # Viral factor based on BLUF length
        bluf_len = len(face_data.get("bluf", ""))
        viral = min(1.0, bluf_len / 100)
        telos = {"viral_factor": viral, "meme": face_data.get("title", "Untitled")}

        return {"ontos": ontos, "chronos": chronos, "topos": topos, "telos": telos}


def main():
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        if cmd == "evolve":
            factory = GenesisFactory()
            factory.evolve()
        elif cmd == "crystallize":
            factory = GenesisFactory()
            factory.crystallize()
        elif cmd == "scan":
            scanner = GenesisScanner()
            scanner.scan()
        else:
            console.print(f"[red]Unknown command: {cmd}[/red]")
            console.print("Usage: python genesis.py [scan|evolve|crystallize]")
    else:
        scanner = GenesisScanner()
        scanner.scan()

        # Optional: Run smoke tests if requested
        if "--venom" in sys.argv:
            console.print("\n[bold blue]🧪 Venom Protocol[/bold blue]")
            console.print("[bold]🚀 Injecting Venom...[/bold]")
            subprocess.run(["make", "test-all"])


if __name__ == "__main__":
    main()
