import os
import asyncio
import logging
from pathlib import Path
from typing import List, Dict
from pydantic import BaseModel, Field
import instructor
from openai import OpenAI

# Setup Logging
logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("phoenix_rise")

# --- 1. The DNA (Pydantic Models) ---


class Conflict(BaseModel):
    description: str = Field(
        ...,
        description="Description of the conflict (e.g., 'File A says X, File B says Y')",
    )
    resolution: str = Field(
        ..., description="Proposed resolution for Gen 51 (e.g., 'Adopt X because...')"
    )


class Gen51FilePlan(BaseModel):
    filename: str = Field(
        ..., description="Name of the file to create (e.g., 'strategy.feature')"
    )
    purpose: str = Field(..., description="Purpose of this file in Gen 51")


class DomainStrategy(BaseModel):
    domain: str = Field(..., description="The domain being analyzed (e.g., 'Strategy')")
    core_concepts: List[str] = Field(
        ..., description="List of 3-5 core concepts to carry forward"
    )
    conflicts: List[Conflict] = Field(
        ..., description="List of conflicts found and their resolutions"
    )
    gen51_files: List[Gen51FilePlan] = Field(
        ..., description="List of files to create in brain/ for Gen 51"
    )
    summary: str = Field(
        ..., description="Executive summary of the Gen 51 strategy for this domain"
    )


# --- 2. The Phoenix Council (Agent) ---


class PhoenixCouncil:
    def __init__(self):
        self.client = instructor.from_openai(
            OpenAI(
                base_url="https://openrouter.ai/api/v1",
                api_key=os.getenv("OPENROUTER_API_KEY"),
            ),
            mode=instructor.Mode.JSON,
        )
        self.model = os.getenv("DEFAULT_MODEL", "x-ai/grok-4.1-fast")

    async def debate(self, domain: str, files: Dict[str, str]) -> DomainStrategy:
        """
        Analyzes a set of files for a domain and synthesizes a Gen 51 strategy.
        """
        logger.info(f"🔥 The Council is debating: {domain} ({len(files)} files)...")

        # Prepare context
        context = ""
        for filename, content in files.items():
            context += f"\n--- FILE: {filename} ---\n{content[:5000]}\n"  # Truncate for context window

        try:
            strategy = self.client.chat.completions.create(
                model=self.model,
                response_model=DomainStrategy,
                messages=[
                    {
                        "role": "system",
                        "content": (
                            "You are the Phoenix Council of Hive Fleet Obsidian. "
                            "We are transitioning from Gen 50 to Gen 51. "
                            "Your task is to review the crystallized memories of Gen 50, "
                            "identify inconsistencies, and propose a consolidated strategy for Gen 51. "
                            "Gen 51 focuses on 'Intent-Based Engineering' (Gherkin + Mermaid). "
                            "Be critical. Discard weak ideas. Strengthen core ones."
                        ),
                    },
                    {
                        "role": "user",
                        "content": f"Analyze these files for the '{domain}' domain and propose a Gen 51 strategy:\n{context}",
                    },
                ],
                max_retries=3,
            )
            return strategy
        except Exception as e:
            logger.error(f"❌ Council failed to debate {domain}: {e}")
            # Return a default strategy or raise
            return DomainStrategy(
                domain=domain,
                core_axiom="Survival",
                key_patterns=["Redundancy"],
                forbidden_patterns=["Fragility"],
                evolutionary_vector="Stasis",
            )


# --- 3. The Ritual (Main Loop) ---


async def main():
    library_path = Path("memory/semantic/library")
    if not library_path.exists():
        logger.error("❌ Library not found. Run ingestion first.")
        return

    council = PhoenixCouncil()
    report_path = Path("venom/PHOENIX_RISE_REPORT.md")

    with open(report_path, "w") as f:
        f.write("# 🔥 Phoenix Rise Report: Gen 51 Strategy\n\n")
        f.write("> **Status**: Generated by The Phoenix Council\n")
        f.write("> **Source**: Gen 50 Crystallized Memory\n\n")

    # Group files by domain
    domains = {}
    for file_path in library_path.glob("**/*"):
        if file_path.is_file():
            domain = file_path.parent.name
            if domain not in domains:
                domains[domain] = {}
            domains[domain][file_path.name] = file_path.read_text(encoding="utf-8")

    # Debate each domain
    for domain, files in domains.items():
        strategy = await council.debate(domain, files)
        if strategy:
            # Append to report
            with open(report_path, "a") as f:
                f.write(f"## 🦅 Domain: {strategy.domain.upper()}\n\n")
                f.write(f"**Summary**: {strategy.summary}\n\n")

                f.write("### 🧠 Core Concepts\n")
                for concept in strategy.core_concepts:
                    f.write(f"*   {concept}\n")
                f.write("\n")

                f.write("### ⚔️ Conflicts & Resolutions\n")
                if strategy.conflicts:
                    for conflict in strategy.conflicts:
                        f.write(f"*   **Conflict**: {conflict.description}\n")
                        f.write(f"    *   **Resolution**: {conflict.resolution}\n")
                else:
                    f.write("*   *No major conflicts found.*\n")
                f.write("\n")

                f.write("### 📂 Gen 51 File Plan\n")
                for plan in strategy.gen51_files:
                    f.write(f"*   `{plan.filename}`: {plan.purpose}\n")
                f.write("\n---\n\n")

            logger.info(f"✅ {domain} strategy crystallized.")

    logger.info(f"✨ Phoenix Rise Report generated at {report_path}")


if __name__ == "__main__":
    asyncio.run(main())
