#!/usr/bin/env python3
"""
🛡️ Hive Guard: Stigmergy Headers
Ensures that every Body file has a Stigmergic Header linking it to Intent.
"""

import sys
from pathlib import Path


def check_headers():
    print("🛡️  Scanning Body for Stigmergic Headers...")

    root_dir = Path(__file__).parent.parent.parent
    hands_dir = root_dir / "body" / "hands"

    # Files to exclude (utilities, __init__, etc.)
    exclusions = ["__init__.py", "tools.py", "prey_agent.py", "swarm_controller.py"]

    files = list(hands_dir.glob("*.py"))
    violations = []

    for file_path in files:
        if file_path.name in exclusions:
            continue

        # Skip test files if they are just runners
        if file_path.name.startswith("test_"):
            continue

        content = file_path.read_text()

        # Check for "Intent:" or "Generated by Genesis" in the first 20 lines
        header_chunk = "\n".join(content.splitlines()[:20])

        has_intent = "Intent:" in header_chunk
        has_genesis = "Generated by Genesis" in header_chunk

        if has_intent or has_genesis:
            print(f"   ✅ {file_path.name} -> Header Found")
        else:
            print(f"   ❌ {file_path.name} -> MISSING STIGMERGY HEADER")
            violations.append(file_path.name)

    if violations:
        print(
            f"\n🚫 Header Check Failed! {len(violations)} files are missing Stigmergic Headers."
        )
        print(
            "   All Body files must declare their Intent or Genesis origin in the docstring."
        )
        sys.exit(1)

    print("\n✅ All Body files are Stigmergically Linked.")
    sys.exit(0)


if __name__ == "__main__":
    check_headers()
